class Country
  def self.menu_selection
    [
     ["United States", "US"],
     ["Canada", "CA"],
     ["United Kingdom", "GB"],
     ["Andorra", "AD"],
     ["Arab Emirates", "AE"],
     ["Antigua And Barbuda", "AG"],
     ["Anguilla", "AI"],
     ["Albania", "AL"],
     ["Armenia", "AM"],
     ["Neth. Antilles", "AN"],
     ["Angola", "AO"],
     ["Argentina", "AR"],
     ["Austria", "AT"],
     ["Australia", "AU"],
     ["Aruba", "AW"],
     ["Azerbaijan", "AZ"],
     ["Bosnia And Herzegovina", "BA"],
     ["Barbados", "BB"],
     ["Bangladesh", "BD"],
     ["Belgium", "BE"],
     ["Bulgaria", "BG"],
     ["Bahrain", "BH"],
     ["Bermuda", "BM"],
     ["Brunei", "BN"],
     ["Bolivia", "BO"],
     ["Brazil", "BR"],
     ["The Bahamas", "BS"],
     ["Botswana", "BW"],
     ["Belarus", "BY"],
     ["Belize", "BZ"],
     ["Cocos Islands", "CC"],
     ["Congo, Democratic Republic Of", "CD"],
     ["Switzerland", "CH"],
     ["Ivory Coast", "CI"],
     ["Cook Islands", "CK"],
     ["Chile", "CL"],
     ["Cameroon", "CM"],
     ["China P.Rep.", "CN"],
     ["Colombia", "CO"],
     ["Costa Rica", "CR"],
     ["Czechoslovakia", "CS"],
     ["Cuba", "CU"],
     ["Cyprus", "CY"],
     ["Czech Republic", "CZ"],
     ["Germany", "DE"],
     ["Denmark", "DK"],
     ["Dominica", "DM"],
     ["Dominican Repl.", "DO"],
     ["Algeria", "DZ"],
     ["Ecuador", "EC"],
     ["Estonia", "EE"],
     ["Egypt", "EG"],
     ["Spain", "ES"],
     ["Ethiopia", "ET"],
     ["Finland", "FI"],
     ["Fiji", "FJ"],
     ["Falkland Islands (Malvinas)", "FK"],
     ["Faroe Islands", "FO"],
     ["France", "FR"],
     ["Gabon", "GA"],
     ["Grenada", "GD"],
     ["Georgia (Republic Of)", "GE"],
     ["French Guiana", "GF"],
     ["Ghana", "GH"],
     ["Gibraltar", "GI"],
     ["Greenland", "GL"],
     ["Gambia", "GM"],
     ["Guinea", "GN"],
     ["Guadeloupe", "GP"],
     ["Greece", "GR"],
     ["Guatemala", "GT"],
     ["Guyana", "GY"],
     ["China,Hong Kong S.A.R.", "HK"],
     ["Honduras", "HN"],
     ["Croatia", "HR"],
     ["Haiti", "HT"],
     ["Hungary", "HU"],
     ["Indonesia", "ID"],
     ["Ireland", "IE"],
     ["Israel", "IL"],
     ["India", "IN"],
     ["Iraq", "IQ"],
     ["Iran", "IR"],
     ["Iceland", "IS"],
     ["Italy", "IT"],
     ["Jamaica", "JM"],
     ["Jordan", "JO"],
     ["Japan", "JP"],
     ["Kenya", "KE"],
     ["Kyrgyzstan", "KG"],
     ["Cambodia", "KH"],
     ["Saint Kitts And Nevis", "KN"],
     ["North Korea", "KP"],
     ["South Korea", "KR"],
     ["Kuwait", "KW"],
     ["Cayman Islands", "KY"],
     ["Kazakhstan", "KZ"],
     ["Laos", "LA"],
     ["Lebanon", "LB"],
     ["St. Lucia", "LC"],
     ["Liechtenstein", "LI"],
     ["Sri Lanka", "LK"],
     ["Liberia", "LR"],
     ["Lithuania", "LT"],
     ["Luxembourg", "LU"],
     ["Latvia", "LV"],
     ["Libya", "LY"],
     ["Morocco", "MA"],
     ["Monaco", "MC"],
     ["Moldova, Republic Of", "MD"],
     ["Madagascar", "MG"],
     ["Marshall Islands", "MH"],
     ["Macedonia, Former Yugoslav Rep.", "MK"],
     ["Mali", "ML"],
     ["Myanmar", "MM"],
     ["Macau", "MO"],
     ["Martinique", "MQ"],
     ["Mauritania", "MR"],
     ["Malta", "MT"],
     ["Mauritius", "MU"],
     ["Malawi", "MW"],
     ["Mexico", "MX"],
     ["Malaysia", "MY"],
     ["Namibia", "NA"],
     ["New Caledonia", "NC"],
     ["Niger", "NE"],
     ["Norfolk Island", "NF"],
     ["Nigeria", "NG"],
     ["Nicaragua", "NI"],
     ["Netherlands", "NL"],
     ["Norway", "NO"],
     ["Nepal", "NP"],
     ["New Zealand", "NZ"],
     ["Oman", "OM"],
     ["Panama", "PA"],
     ["Peru", "PE"],
     ["Fr. Polynesia", "PF"],
     ["New Guinea", "PG"],
     ["Philippines", "PH"],
     ["Pakistan", "PK"],
     ["Poland", "PL"],
     ["Portugal", "PT"],
     ["Palau", "PW"],
     ["Paraguay", "PY"],
     ["Qatar", "QA"],
     ["Romania", "RO"],
     ["Russian Federation", "RU"],
     ["Saudi Arabia", "SA"],
     ["Solomon Islands", "SB"],
     ["Sudan", "SD"],
     ["Sweden", "SE"],
     ["Singapore", "SG"],
     ["Slovenia", "SI"],
     ["Slovakia", "SK"],
     ["Sierra Leone", "SL"],
     ["San Marino", "SM"],
     ["Senegal", "SN"],
     ["Suriname", "SR"],
     ["U.S.S.R.", "SU"],
     ["El Salvador", "SV"],
     ["Syria", "SY"],
     ["Swaziland", "SZ"],
     ["Turks And Caicos Islands", "TC"],
     ["Chad", "TD"],
     ["Thailand", "TH"],
     ["Tunisia", "TN"],
     ["Turkey", "TR"],
     ["Trinidad/Tobago", "TT"],
     ["Taiwan", "TW"],
     ["Tanzania", "TZ"],
     ["Ukraine", "UA"],
     ["Uganda", "UG"],
     ["Uruguay", "UY"],
     ["Uzbekistan", "UZ"],
     ["Vatican City State (Holy See)", "VA"],
     ["St. Vincent/Grenadines", "VC"],
     ["Venezuela", "VE"],
     ["Virgin (British) Islands", "VG"],
     ["Viet Nam", "VN"],
     ["Vanuatu (New Hebrides)", "VU"],
     ["Yemen", "YE"],
     ["Yugoslavia", "YU"],
     ["South Africa", "ZA"],
     ["Zambia", "ZM"],
     ["Zimbabwe", "ZW"],
    ]
  end
end
